url: "http://davidlynch.org"
highlighter: rouge
permalink: /blog/:year/:month/:title/

exclude: ["Rakefile", "README.markdown"]

paginate: 10
paginate_path: "/blog/page/:num"

sitename: "David Lynch"
subtitle: "is not a director"

author: "David Lynch"
email: "kemayo@gmail.com"

tag_dir: "blog/tag"

plugins:
  - jekyll-tagging-related_posts
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate
